export const locations = [
{ value: 'location' },
{ value: 'Aan De Wijnlanden Estate' },
{ value: 'Acorn Creek Lifestyle Estate' },
{ value: 'Admirals Kloof' },
{ value: 'Admirals Park' },
{ value: 'Amanda Glen' },
{ value: 'Amandelsig' },
{ value: 'Anchorage Park' },
{ value: 'Athlone' },
{ value: 'Atlantic Beach Golf Estate' },
{ value: 'Atlantic Hills' },
{ value: 'Atlantis Central' },
{ value: 'Atlantis Industrial' },
{ value: 'Audas Estate' },
{ value: 'Aurora' },
{ value: 'Avalon Estate' },
{ value: 'Avondale Parow' },
{ value: 'Bakkershoogte' },
{ value: 'Bakoven' },
{ value: 'Bantry Bay' },
{ value: 'Bardale Village' },
{ value: 'Baronetcy Estate' },
{ value: 'Bay View' },
{ value: 'Bay View Village' },
{ value: 'Beachfront' },
{ value: "Bel'Aire" },
{ value: 'Belgravia' },
{ value: 'Belhar' },
{ value: 'Bellair' },
{ value: 'Belle Constantia' },
{ value: 'Bellville CBD' },
{ value: 'Bellvue' },
{ value: 'Belmont Park' },
{ value: 'Belthorn Estate' },
{ value: 'Belvedere' },
{ value: 'Bergsig' },
{ value: 'Bergvliet' },
{ value: 'Big Bay' },
{ value: 'Bishop Lavis' },
{ value: 'Bishopscourt' },
{ value: 'Bizweni' },
{ value: 'Blaauwbergstrand' },
{ value: 'Blommendal' },
{ value: 'Blomtuin' },
{ value: 'Blouberg Rise' },
{ value: 'Blouberg Sands' },
{ value: 'Bloubergrant' },
{ value: 'Bluewater Estate' },
{ value: 'Bo Oakdale' },
{ value: 'Bongweni' },
{ value: 'Bonnie Brae' },
{ value: 'Bosbell' },
{ value: 'Boskloof Eco Estate' },
{ value: 'Bosonia' },
{ value: 'Boston' },
{ value: 'Bothasig' },
{ value: 'Bracken Heights' },
{ value: 'Brackenfell Central' },
{ value: 'Brackenfell South' },
{ value: 'Braeview' },
{ value: 'Bridgetown' },
{ value: 'Bridgewater' },
{ value: 'Briza' },
{ value: 'Brooklyn' },
{ value: 'Buh-Rein Estate' },
{ value: 'Burgundy' },
{ value: 'Burgundy Estate' },
{ value: 'Camps Bay' },
{ value: 'Cape Town City Centre' },
{ value: 'Capri' },
{ value: 'Century City' },
{ value: 'Chantecler' },
{ value: 'Churchill Estate' },
{ value: 'Clara Anna Fontein' },
{ value: 'Claremont' },
{ value: 'Claremont Village' },
{ value: 'Clifton' },
{ value: 'Clovelly' },
{ value: 'Colorado Park' },
{ value: 'Constantia' },
{ value: 'Cravenby' },
{ value: 'Crawford' },
{ value: 'Croydon Vineyard Estate' },
{ value: "D'Urbanvale" },
{ value: 'De Bron' },
{ value: 'De Kuilen' },
{ value: 'De Oude Spruit' },
{ value: 'De Tijger' },
{ value: 'De Velde' },
{ value: 'De Werf' },
{ value: 'De Wijnlanden Residential Estate' },
{ value: 'De Zicht Estate' },
{ value: 'Dennegeur' },
{ value: 'Dennendal' },
{ value: 'Dido Valley' },
{ value: 'Die Bos' },
{ value: 'Die Wingerd' },
{ value: 'Diep River' },
{ value: 'Door De Kraal' },
{ value: 'Dornhill' },
{ value: 'Durbanville' },
{ value: 'Durbanville Hills' },
{ value: 'Durbanville Rural' },
{ value: 'Duynefontein' },
{ value: 'Edenpark' },
{ value: 'Edgemead' },
{ value: 'Eensgevonden' },
{ value: 'Erica Township' },
{ value: 'Erinvale Estate' },
{ value: 'Eversdal' },
{ value: 'Faerie Knowe' },
{ value: 'Fairfield Estate' },
{ value: 'Fairhaven Country Estate' },
{ value: 'Fairview Golf Estate' },
{ value: 'Ferndale' },
{ value: 'Ferness Estate' },
{ value: 'Fernwood' },
{ value: 'Firgrove' },
{ value: 'Firlands' },
{ value: 'Fish Hoek' },
{ value: 'Flamingo Vlei' },
{ value: 'Forest Glade' },
{ value: 'Fountain Village' },
{ value: 'Fresnaye' },
{ value: 'Froggy Farm' },
{ value: 'Gardens' },
{ value: 'Gatesville' },
{ value: 'Gleemoor' },
{ value: 'Glen Marine' },
{ value: 'Glencairn' },
{ value: 'Glenhaven' },
{ value: 'Glenlily' },
{ value: 'Goedehoop' },
{ value: 'Goedemoed' },
{ value: 'Golden Acre' },
{ value: 'Golf Course' },
{ value: 'Goodwood Estate' },
{ value: 'Goodwood Ext 1' },
{ value: 'Goodwood Park' },
{ value: 'Gordons Bay' },
{ value: 'Gordons Bay Village' },
{ value: 'Graanendal' },
{ value: 'Grassy Park' },
{ value: 'Green Point' },
{ value: 'Greenways' },
{ value: 'Groenvallei' },
{ value: 'Guldenland' },
{ value: 'Haasendal' },
{ value: 'Hagley' },
{ value: 'Harbour Island' },
{ value: 'Harfield Village' },
{ value: 'Heartland Beach Road Precinct' },
{ value: 'Heather Park' },
{ value: 'Heathfield' },
{ value: 'Helderberg Estate' },
{ value: 'Helderrand' },
{ value: 'Heldervue' },
{ value: 'Helena Heights' },
{ value: 'Heritage Park' },
{ value: 'High Constantia' },
{ value: 'High Riding' },
{ value: 'Highbury Park' },
{ value: 'Hoheizen' },
{ value: 'Hyde Park' },
{ value: 'Illaire' },
{ value: 'Imhoffs Gift' },
{ value: 'Jacarandas' },
{ value: 'Joostenbergvlakte Smallholdings' },
{ value: 'Kaapzicht' },
{ value: 'Kelderhof' },
{ value: 'Kempenville' },
{ value: 'Kenever' },
{ value: 'Kenilworth' },
{ value: 'Kenridge' },
{ value: 'Kensington' },
{ value: 'Kenwyn' },
{ value: 'Khaya' },
{ value: 'Kirstenhof' },
{ value: 'Klein Nederburg' },
{ value: 'Kleinbosch' },
{ value: 'Kleinbron' },
{ value: 'Klipdam' },
{ value: 'Klipheuwel Housing Scheme' },
{ value: 'Klipkop' },
{ value: 'Kommetjie' },
{ value: 'Kraaifontein East' },
{ value: 'Kuilsrivier South Smallholdings' },
{ value: 'Kuyasa' },
{ value: 'La Concorde' },
{ value: 'La Montagne' },
{ value: 'La Sandra' },
{ value: 'Labiance' },
{ value: 'Lagoon Beach' },
{ value: 'Lake Michelle Security and Eco Estate' },
{ value: 'Langeberg Hoogte' },
{ value: 'Langeberg Ridge' },
{ value: 'Lansdowne' },
{ value: 'Lentegeur' },
{ value: 'Lochnerhof' },
{ value: 'Loevenstein' },
{ value: 'Longdown Estate' },
{ value: 'Lotus River' },
{ value: 'Loucharmante' },
{ value: 'Maitland' },
{ value: 'Mandalay' },
{ value: 'Mansfield' },
{ value: 'Meadowridge' },
{ value: 'Melkbosch Strand' },
{ value: 'Milnerton' },
{ value: 'Milnerton Ridge' },
{ value: 'Montclair' },
{ value: 'Monte Sereno' },
{ value: 'Monte Vista' },
{ value: 'Morgenster' },
{ value: 'Mouille Point' },
{ value: 'Mountainside' },
{ value: 'Mountview' },
{ value: 'Mowbray' },
{ value: 'Murdock Valley' },
{ value: 'Mzuri Estate' },
{ value: 'Natures Valley' },
{ value: 'Ndabeni' },
{ value: 'New Macassar Village' },
{ value: 'New Scheme' },
{ value: 'Newlands' },
{ value: 'Noordhoek' },
{ value: 'Noordhoek Manor' },
{ value: 'Normandie' },
{ value: "O'Kennedyville" },
{ value: 'Oakdale' },
{ value: 'Oakglen' },
{ value: 'Observatory' },
{ value: 'Olive Grove' },
{ value: 'Onverwacht' },
{ value: 'Oosterzee-Bellville' },
{ value: 'Ottery' },
{ value: 'Oude Westhof' },
{ value: 'Paarde Vlei' },
{ value: 'Panorama' },
{ value: 'Parel Vallei' },
{ value: 'Parklands' },
{ value: 'Parks Estate' },
{ value: 'Parow' },
{ value: 'Parow East' },
{ value: 'Parow North' },
{ value: 'Parow Valley' },
{ value: 'Pearl Marina' },
{ value: 'Pearlrise' },
{ value: 'Peerless Park North' },
{ value: 'Penhill' },
{ value: 'Penlyn Estate' },
{ value: 'Pine Acres' },
{ value: 'Pinehurst' },
{ value: 'Pinelands' },
{ value: 'Plattekloof 1' },
{ value: 'Plattekloof 2' },
{ value: 'Plattekloof 3' },
{ value: 'Plattekloof Glen' },
{ value: 'Plumstead' },
{ value: 'Polkadraai Security Estate' },
{ value: 'Portland' },
{ value: 'Protea Heights' },
{ value: 'Protea Valley' },
{ value: 'Ravensmead' },
{ value: 'Retreat' },
{ value: 'Richmond Estate' },
{ value: 'Richmond Park' },
{ value: 'Richwood' },
{ value: 'Ridgeworth' },
{ value: 'Rivergate' },
{ value: 'Rocklands' },
{ value: 'Rome Glen' },
{ value: 'Rondebosch' },
{ value: 'Rondebosch East' },
{ value: 'Rosebank' },
{ value: 'Rosedale' },
{ value: 'Rosedale Estate' },
{ value: 'Rosendal' },
{ value: 'Rosenpark' },
{ value: 'Roundhay' },
{ value: 'Rouxville' },
{ value: 'Royal Ascot' },
{ value: 'Rugby' },
{ value: 'Rustdal' },
{ value: 'Ruyterwacht' },
{ value: 'Rylands' },
{ value: 'Sagewood' },
{ value: 'Salt River' },
{ value: 'Sanddrift' },
{ value: 'Sandown' },
{ value: 'Sandvlei' },
{ value: 'Sarepta' },
{ value: 'Scarborough' },
{ value: 'Schapenberg Estate' },
{ value: 'Schonenberg' },
{ value: 'Schoongezicht' },
{ value: 'Scottsdene' },
{ value: 'Scottsville' },
{ value: 'Sea Point' },
{ value: 'Sherwood' },
{ value: 'Silver Oaks' },
{ value: 'Silverglade' },
{ value: 'Silvertown' },
{ value: 'Silvertree Estate' },
{ value: "Simon's Town" },
{ value: 'Sir Lowrys Pass' },
{ value: 'Sitari Country Estate' },
{ value: 'Somerset Forest' },
{ value: 'Somerset Lakes' },
{ value: 'Somerset Park' },
{ value: 'Somerset Ridge' },
{ value: 'Somerset West' },
{ value: 'Somerset West Rural' },
{ value: 'Soneike I' },
{ value: 'Sonkring' },
{ value: 'Sonnendal' },
{ value: 'Sonstraal' },
{ value: 'Sonstraal Heights' },
{ value: 'Southfield' },
{ value: 'Southfork' },
{ value: 'Spanish Farm' },
{ value: 'Springbok Park' },
{ value: 'Steenberg' },
{ value: 'Steenbras View' },
{ value: 'Stellenberg' },
{ value: 'Stellendale' },
{ value: 'Stellenridge' },
{ value: 'Stellenryk' },
{ value: 'Steynsrust' },
{ value: 'Stikland Industrial' },
{ value: 'Stonehaven Estate' },
{ value: 'Stonehurst Mountain Estate' },
{ value: 'Stonewood Security Estate' },
{ value: 'Strand' },
{ value: 'Strandfontein' },
{ value: 'Summer Greens' },
{ value: 'Sun Valley' },
{ value: 'Sunlands' },
{ value: 'Sunningdale' },
{ value: 'Sunnydale' },
{ value: 'Sunridge' },
{ value: 'Sunset Beach' },
{ value: 'Sunset Glen' },
{ value: 'Sunset Links' },
{ value: 'Surrey Estate' },
{ value: 'Sybrand Park' },
{ value: 'Table View' },
{ value: 'The Boulders' },
{ value: 'The Conifers' },
{ value: 'The Crest' },
{ value: 'The Vines Estate' },
{ value: 'Thornton' },
{ value: 'Three Anchor Bay' },
{ value: 'Tijgerhof' },
{ value: 'Tokai' },
{ value: 'Townsend Estate' },
{ value: 'Tre Donne' },
{ value: 'Turf Hall Estate' },
{ value: 'Twin Palms' },
{ value: 'Tygerdal' },
{ value: 'Tygerfalls' },
{ value: 'Tygervalley' },
{ value: 'Tygervalley Waterfront' },
{ value: 'Uitzicht' },
{ value: 'Valmary Park' },
{ value: 'Van Riebeeckshof' },
{ value: 'Van Riebeeckstrand' },
{ value: 'Van Ryneveld' },
{ value: 'Vanguard' },
{ value: 'Vasco Estate' },
{ value: 'Vergesig' },
{ value: 'Vierlanden' },
{ value: 'Viking Village' },
{ value: 'Vredehoek' },
{ value: 'Vredekloof' },
{ value: 'Vredekloof East' },
{ value: 'Vredekloof Heights' },
{ value: 'Vredenberg-Bellville' },
{ value: 'Vygeboom' },
{ value: 'Waves Edge' },
{ value: 'Welgedacht' },
{ value: 'Welgelee' },
{ value: 'Welgelegen' },
{ value: 'Welgemoed' },
{ value: 'Wellway Park' },
{ value: 'West Beach' },
{ value: 'West Riding' },
{ value: 'Westgate' },
{ value: 'Westlake' },
{ value: 'Westridge - Mitchells Plain' },
{ value: 'Wetton' },
{ value: 'Whispering Pines' },
{ value: 'Windsor Park' },
{ value: 'Winslow' },
{ value: 'Woodbridge Island' },
{ value: 'Woodlands' },
{ value: 'Wynberg' },
{ value: 'Zevenwacht Country Estate' },
{ value: 'Zevenwacht Retirement Village' },
{ value: 'Zevenzicht' },
{ value: 'Zilvermyn Estate' },
{ value: 'Zoo Park' }]
