# Use the official Python 3.9 image
FROM python:3.9

# Set the working directory to /code
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY . /code

# Install the dependencies from your requirements.txt
RUN pip install -r requirements.txt


CMD uvicorn main:app --host 0.0.0.0 --port $PORT